---
version: "3"

networks:
  gitea:
    external: false

services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /mnt/tvshows:/tvshows
      - /mnt/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    dns:
      - 9.9.9.9
      - 1.1.1.1
    environment:
      - TZ=Europe/Brussels
    ports:
      - 5055:5055
    volumes:
      - /home/pi/docker/overseerr:/app/config
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /mnt/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/tvshows:/tvshows
      - /mnt/movies:/movies
      - /mnt/music:/music
      - /mnt/media:/media
      - /mnt/photos:/pictures
      - ./plex_config:/config
    restart: unless-stopped
  
  tautulli:
    container_name: tautulli
    image: ghcr.io/tautulli/tautulli
    ports:
      - 8181:8181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    restart: unless-stopped
    volumes:
      - ./tautulli_config:/config

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      - TZ=Europe/Brussels
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  minimserver:
    image: minimworld/minimserver
    container_name: MinimServer
    volumes:
      - "/mnt/music:/Music"
    environment:
      - TZ=Europe/Brussels
    network_mode: host
    restart: unless-stopped

  songkong:
    image: songkong/songkong
    container_name: SongKong
    volumes:
      - "/mnt/music:/music"
      - "/home/tom/docker/songkong:/songkong"
    environment:
      - TZ=Europe/Brussels
    network_mode: host
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - "/mnt/music:/music"
      - "/mnt/downloads:/downloads"
      - "./lidarr_config:/config"
    ports:
      - 8686:8686
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - 9000:9000

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - "./jackett_config:/config"
      - "/mnt/downloads/jackett:/downloads"
    ports:
      - 9117:9117
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=115
      - USER_GID=124
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/storage/gitea:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
